spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=schoolboy
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.test.database.replace=none

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.info.title=User Service API
springdoc.info.description=API for user management
springdoc.info.version=1.0
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.tryItOutEnabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8080